version: "3"
services:
  authenticatie-service-dev:
    build: .
    image: authenticatie_service
    networks:
      - microservice
    command: npm start
    restart: on-failure
    links:
      - authenticatie-db-dev
    ports:
      - "8093:8093"
    environment:
      MESSAGING_SERVICE: messaging-service-dev
      MESSAGING_SERVICE_PORT: 8097
      STUDENT_SERVICE: student-service-dev
      STUDENT_SERVICE_PORT: 8095
      FRONTEND_ADDRESS: 145.97.16.182
      FRONTEND_PORT: 8086
      DB_HOST: authenticatie-db-dev
      PORT: 8093
      JWT_SECRET: pojiaj234oi234oij234oij4
      ADMIN_KEY: bkJ2pI9fFepBxMs9DlpyaBOYcbTT14wF
  authenticatie-db-dev:
    image: mongo:3.4
    networks:
      - microservice
    volumes:
      - authenticatie-vm-dev:/data/db

volumes:
  authenticatie-vm-dev:

networks:
    microservice:
      external: true